apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - namespace.yaml
  - secret.yaml
  - httproute.yaml
configMapGenerator:
  - name: bkw-grafana-dashboards
    files:
      - dashboards/bkw.json
    options:
      labels:
        grafana_dashboard: "1"
