chartMode: standalone
clusterName: teleport.<YOUR_DOMAIN>
kubeClusterName: oci
proxyListenerMode: multiplex
auth:
  teleportConfig:
    auth_service:
      authentication:
        type: github
authentication:
  type: github
  localAuth: true
  secondFactor: on
highAvailability:
  replicaCount: 1
  certManager:
    enabled: true
    issuerName: letsencrypt
    issuerKind: ClusterIssuer
operator:
  enabled: true
ingress:
  enabled: false
proxy:
  highAvailability:
    replicaCount: 1
  service:
    type: LoadBalancer
  annotations:
    service:
      external-dns.alpha.kubernetes.io/hostname: teleport.<YOUR_DOMAIN>
      oci.oraclecloud.com/load-balancer-type: "nlb"
      oci-network-load-balancer.oraclecloud.com/oci-network-security-groups: "ocid1.networksecuritygroup.oc1.ap-tokyo-1.<YOUR_NSG_OCID>"
