apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: GIT_REPO_URL  # Replace with your repository URL
    targetRevision: HEAD
    path: gitops/core/cert-manager/issuer
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
