apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  sources:
    - repoURL: oci://docker.io/envoyproxy
      chart: gateway-helm
      targetRevision: 1.6.1
    - repoURL: GIT_REPO_URL  # Replace with your repository URL
      targetRevision: HEAD
      path: gitops/core/envoy-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
