apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.5.5
      helm:
        values: |
          grafana.ini:
            app_mode: production
            server:
              domain: monitoring.nce.wtf
              root_url: https://monitoring.nce.wtf
            users:
              allow_sign_up: false
            auth:
              disable_login_form: true
            auth.generic_oauth:
              enabled: true
              name: Dex
              allow_sign_up: true
              client_id: $__file{/etc/secrets/dex_grafana_client/client-id}
              client_secret: $__file{/etc/secrets/dex_grafana_client/client-secret}
              scopes: openid profile email groups
              email_attribute_path: email
              auth_url: https://login.nce.wtf/dex/auth
              token_url: https://login.nce.wtf/dex/token
              api_url: https://login.nce.wtf/dex/userinfo
              role_attribute_path: contains(groups[*], 'nce-acme:admin') && 'Admin' || 'Viewer'
          extraSecretMounts:
            - name: dex-grafana-client
              secretName: dex-grafana-client
              defaultMode: 0440
              mountPath: /etc/secrets/dex_grafana_client
              readOnly: true
          plugins:
            - oci-metrics-datasource
          ingress:
            enabled: false
          sidecar:
            dashboards:
              enabled: true
              logLevel: INFO
              searchNamespace: grafana
              label: grafana_dashboard
            datasources:
              enabled: true
              searchNamespace: grafana
    - repoURL: GIT_REPO_URL  # Replace with your repository URL
      targetRevision: HEAD
      path: gitops/core/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
