apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.10.1
      helm:
        values: |
          defaultSettings:
            storageMinimalAvailablePercentage: 10
          persistence:
            defaultClassReplicaCount: 2
          ingress:
            enabled: false
    - repoURL: GIT_REPO_URL  # Replace with your repository URL
      targetRevision: HEAD
      path: gitops/core/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
